version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://user:password@db:5432/backend-test
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run start

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend-test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
